image: docker/compose:latest
services:
  - docker:dind

stages:  
  - maven-compile # build
  - build #Docker compose up step
  - docker-deploy # Docker Hub
  - terraform-job
  - validate
  - plan
  - apply



maven-job:
  image: maven
  stage: maven-compile
  script:
    - sh Jars.sh
  artifacts:
    paths:
      - user_service/target/*.jar
      - contact_service/target/*.jar

build-job:    
  stage: build
  dependencies:
    - maven-job
  script:
    - echo "Compiling the code..."
    - docker-compose up --build -d
    - echo "Compile complete."


docker-job:
  stage: docker-deploy
  dependencies:
    - maven-job
  script:
    - sh Docker_Deploy.sh

terraform:
  image: 
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform init
  stage: terraform-job
  script:
    echo "started"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual

 

