image: docker/compose:latest
services:
  - docker:dind

stages:  
  - maven-compile # Compile
  - test # Test
  - build # Docker compose up step
  - docker-deploy # Docker Hub
  - terraform-job # Terraform 
  - ansible-job # Ansible

# maven-job:
#   image: maven
#   stage: maven-compile
#   script:
#     - sh Jars.sh
#   artifacts:
#     paths:
#       - user_service/target/*.jar
#       - contact_service/target/*.jar

# build-job:    
#   stage: build
#   dependencies:
#     - maven-job
#   script:
#     - echo "Compiling the code..."
#     - docker-compose up --build -d
#     - echo "Compile complete."


# docker-job:
#   stage: docker-deploy
#   dependencies:
#     - maven-job
#   script:
#     - sh Docker_Deploy.sh

# terraform:
#   image: 
#     name: hashicorp/terraform:light
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#   before_script:
#   - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
#   - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
#   - rm -rf .terraform
#   - cd Terraform/Project
#   - terraform --version
#   - terraform init
#   artifacts:
#     paths:
#       - Terraform/Project/inventory/hosts

#   stage: terraform-job 
#   script:
#     - echo "started"
#     - sh make.sh

ansible:
  image: registry.gitlab.com/torese/docker-ansible
  # extends: terraform
  # dependencies:
  #   - terraform
  before_script:
    # - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    # - eval $(ssh-agent -s)
    # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add terraform.pem
    - cd terraform/Project
    - export ANSIBLE_HOST_KEY_CHECKING=False
  stage: ansible-job
  script:
    - ansible-playbook -i inventory/hosts playbook.yml