image: docker/compose:latest
services:
  - docker:dind

stages:  
  - maven-compile # Build
  - build # Docker compose up step
  - docker-deploy # Docker Hub
  - terraform-job # Terraform 

maven-job:
  image: maven
  stage: maven-compile
  script:
    - sh Jars.sh
  artifacts:
    paths:
      - user_service/target/*.jar
      - contact_service/target/*.jar

build-job:    
  stage: build
  dependencies:
    - maven-job
  script:
    - echo "Compiling the code..."
    - docker-compose up --build -d
    - echo "Compile complete."


docker-job:
  stage: docker-deploy
  dependencies:
    - maven-job
  script:
    - sh Docker_Deploy.sh

terraform:
  image: 
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - cd Terraform/Project
  - terraform --version
  - terraform init
  stage: terraform-job
  artifacts:
    paths:
      - planfile  
  script:
    - echo "started"
    - terraform validate
    - terraform plan -out "planfile" -var-file="var.tfvars"
    - terraform apply -var-file="var.tfvars" --auto-approve
    
  when: manual
