version: '3.1'
services:
  postgresqldb:
    image: postgres
    container_name: Appsql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data

  user_service:
    container_name: userapp
    build: ./user_service/
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - postgresqldb

  contact_service:
    container_name: contactapp
    restart: on-failure
    build: ./contact_service/
    ports:
      - "8081:8081"
    depends_on:
      - postgresqldb


volumes:
  db:
