version: '3.1'
services:
  postgresqldb:
    image: postgres
    container_name: springpsql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql
    networks:
      - app-net

  user_service:
    container_name: userapp
    build: ./user_service/
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - postgresqldb
#    environment:
#      - WAIT_HOSTS=contact_service:8081
#      - WAIT_HOSTS=postgresqldb:5433
    networks:
      - app-net


  contact_service:
    container_name: contactapp
    restart: on-failure
    build: ./contact_service/
    ports:
      - "8081:8081"
    depends_on:
      - postgresqldb
#    environment:
#      - WAIT_HOSTS=postgresqldb:5433
    networks:
      - app-net



volumes:
  db:

networks:
  app-net:


