version: 2.1

orbs:
  terraform: circleci/terraform@3.0.1
  aws-cli: circleci/aws-cli@2.0
  
jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME

  build-package:
    docker:
      - image: cimg/openjdk:15.0.1
        auth:
          username: anil76201
          password: Reddy@0108
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: false
      - run:
          name: Build Contact Service
          command: |
            cd contact_service; 
            mvn clean package;
            docker login -u "anil76201" -p "Reddy@0108";
            docker build -t anil76201/contactimage .;
            docker push anil76201/contactimage;
          working_directory: .
      - run:
          name: Build User Service
          command: |
            cd user_service; 
            mvn clean package;
            docker login -u "anil76201" -p "Reddy@0108";
            docker build -t anil76201/userimage .;
            docker push anil76201/userimage;
          working_directory: .
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_artifacts:
          path: ./user_service/target/user_service-0.0.1-SNAPSHOT.jar
          destination: ./user_service.jar
      - store_artifacts:
          path: ./contact_service/target/contact_service-0.0.1-SNAPSHOT.jar
          destination: ./contact_service.jar
  
  terraform-job:
    docker:
      - image: cimg/base:stable
    steps:
      - terraform/install
      - run:
          name: Get&Run Terraform Scripts
          command: |
            git clone https://gitlab.com/SivaKumarK1/Terraform;
            cd Terraform;
            terraform init;
            terraform validate;
            terraform plan
      - run:
          name: Apply Terraform
          command: |
            

  test-job: # this is to run devops test commands like ls pwd or same type  
    docker:
      - image: cimg/openjdk:11.0
    steps:
        - run:
            command: |
              pwd;
              ls;

workflows:
  lincker: 
    jobs:
      - aws-cli-cred-setup
      - build-package
      - build-package
      - test-job
      - terraform-job