version: 2.1
jobs:
  build-package:
    docker:
      - image: cimg/openjdk:15.0.1
        auth:
          username: anil76201
          password: Reddy@0108
    # working_directory: ~/Micro_Service_Postgres
    steps:
      - checkout
      - run:
          name: Build Contact Service
          command: |
            cd contact_service; 
            mvn clean package;
            pwd;
            ls -R;
            docker build -t anil76201/contactimage .
          working_directory: .
      - run:
          name: Build User Service
          command: |
            cd user_service; 
            mvn clean package;
            pwd
            ls -R;
            docker build -t anil76201/userimage .
          working_directory: .
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_artifacts:
          path: ./user_service/target/user_service-0.0.1-SNAPSHOT.jar
          destination: ./user_service.jar
      - store_artifacts:
          path: ./contact_service/target/contact_service-0.0.1-SNAPSHOT.jar
          destination: ./contact_service.jar
  test-job: # this is to run devops test commands like ls pwd or same type  
    docker:
      - image: cimg/openjdk:11.0
    steps:
        - run:
            command: |
              pwd;
              ls;

workflows:
  lincker: 
    jobs:
      - build-package
      - build-package
      - test-job