version: 2.1
jobs:   
  build-package:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: anil76201
          password: Reddy@0108
    # working_directory: ~/Micro_Service_Postgres
    steps:
      - checkout
      - run:
          name: Build Contact Service
          command: |
            cd Micro_Service_Postgres/contact_service; 
            mvn clean package;
            docker build -t anil76201/contactimage ./Micro_Service_Postgres/contact_service
            ls;
            ls -R | grep .jar;
            pwd;
      - run:
          name: Build User Service
          command: |
            cd Micro_Service_Postgres/user_service; 
            mvn clean package;
            docker build -t anil76201/userimage ./Micro_Service_Postgres/user_service  
            ls;
            ls -R | grep .jar;
            pwd;     

  test-job: # this is to run devops test commands like ls pwd or same type  
    docker:
      - image: cimg/openjdk:11.0
    steps:
        - run:
            command: |
              pwd;
              ls;

workflows:
  lincker: 
    jobs:
      - build-package
      - build-package
      - test-job